export const metadata = {
  title: 'Community Impact | StreetSense',
  description: 'See the real-world impact StreetSense users are making in their neighborhoods.',
};

export default function ImpactPage() {
  const successStories = [
    {
      id: 1,
      title: "Maple Street Pothole Fixed in 24 Hours",
      description: "After being reported by 5 different neighbors using StreetSense, the city prioritized the massive pothole on Maple Street. It was filled and paved the very next day.",
      category: "Road Repair",
      date: "Oct 12, 2026"
    },
    {
      id: 2,
      title: "Downtown Lighting Restored",
      description: "A string of 4 broken streetlights left a block in complete darkness. The community rallied on StreetSense, and the electrical grid was repaired within a week, restoring safety.",
      category: "Public Safety",
      date: "Sep 28, 2026"
    },
    {
      id: 3,
      title: "Graffiti Cleaned at Local Park",
      description: "Offensive graffiti at the children's park was reported on Saturday morning. By Sunday evening, the parks department had completely removed it.",
      category: "Vandalism",
      date: "Sep 15, 2026"
    }
  ];

  return (
    <main>
      <section className="section-padding light-bg" style={{ paddingTop: '10rem' }}>
        <div className="container">
          <div className="section-header text-center">
            <div className="badge">Real Results</div>
            <h1>Our Community <span className="highlight">Impact</span></h1>
            <p style={{ maxWidth: '800px', margin: '0 auto' }}>
              StreetSense isn't just about reporting issues—it's about getting them solved. 
              Look at the numbers generated by active citizens making their neighborhoods safer and cleaner.
            </p>
          </div>
          
          <div className="stats" style={{ justifyContent: 'center', marginTop: '4rem', flexWrap: 'wrap' }}>
            <div className="stat-item" style={{ textAlign: 'center' }}>
              <span className="stat-number">1,245</span>
              <span className="stat-label">Total Issues Resolved</span>
            </div>
            <div className="stat-item" style={{ textAlign: 'center' }}>
              <span className="stat-number">48h</span>
              <span className="stat-label">Average Response Time</span>
            </div>
            <div className="stat-item" style={{ textAlign: 'center' }}>
              <span className="stat-number">500+</span>
              <span className="stat-label">Active Citizens</span>
            </div>
            <div className="stat-item" style={{ textAlign: 'center' }}>
              <span className="stat-number">12</span>
              <span className="stat-label">Neighborhoods Reached</span>
            </div>
          </div>
        </div>
      </section>

      <section className="section-padding">
        <div className="container">
          <div className="section-header text-center">
            <h2>Success Stories</h2>
            <p>Real issues reported by users, resolved by the community.</p>
          </div>
          
          <div className="features-grid">
            {successStories.map((story) => (
              <div key={story.id} className="feature-card glass-panel" style={{ position: 'relative', overflow: 'hidden' }}>
                <div style={{ position: 'absolute', top: '0', left: '0', width: '100%', height: '4px', background: 'var(--accent-green)' }}></div>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '1rem', fontSize: '0.85rem', color: 'var(--text-muted)' }}>
                  <span style={{ fontWeight: '600', color: 'var(--primary-blue)' }}>{story.category}</span>
                  <span>{story.date}</span>
                </div>
                <h3>{story.title}</h3>
                <p>{story.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
      
      <section className="cta section-padding light-bg">
        <div className="container">
          <div className="cta-card glass-panel text-center">
            <h2>Be Part of the Impact</h2>
            <p>Your single report can make a street safer for everyone. Join our prototype today.</p>
            <div style={{ marginTop: '2rem' }}>
              <a href="/#cta" className="btn btn-primary btn-large">Get Early Access</a>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}
